image: java:8-jdk

stages:
  - build
  - test
  
cache:
  paths:
    - .cache/gradle/caches
    - .cache/gradle/wrapper

build:
  allow_failure: false
  script:
    - ./gradlew -g .cache/gradle clean assemble
  stage: build

test:
  script:
    - ./gradlew -g .cache/gradle --stacktrace
  stage: test
