image: java:8-jdk

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .cache/gradle/caches
    - .cache/gradle/wrapper
    
build:
  allow_failure: false
  script:
    - chmod +x ./gradlew
    - ./gradlew -g .cache/gradle clean assemble
  only:
    - master
  stage: build
 

test:
  script:
    - chmod +x ./gradlew
    - ./gradlew -g .cache/gradle check --stacktrace
  only:
    - master
  stage: test
 
deploy:
  script:
   - git remote add heroku https://heroku:1f812ae7-e18d-4f60-89c8-ebd0f1fb9b05@git.heroku.com/kandoe.git
   - git config --global user.email "lander.tuyteleers@student.kdg.be"
   - git config --global user.name "Lander Tuyteleers"
   - git push -f heroku master
   - echo "Deployed to staging server"
     only:
    - master
  stage: deploy
