image: java:8-jdk

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .cache/gradle/caches
    - .cache/gradle/wrapper
    
build:
  allow_failure: false
  script:
    - chmod +x ./gradlew
    - ./gradlew -g .cache/gradle clean assemble
  stage: build

test:
  script:
    - chmod +x ./gradlew
    - ./gradlew -g .cache/gradle check --stacktrace
  stage: test
 
deploy:
  script:
    - sudo add-apt-repository "deb https://cli-assets.heroku.com/branches/stable/apt ./"
    - curl -L https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get install heroku
    - heroku buildpacks:set heroku/java
    - git remote add heroku https://heroku:1f812ae7-e18d-4f60-89c8-ebd0f1fb9b05@git.heroku.com/kandoe.git
    - git push -f heroku master
  stage: deploy
